spring.config.import=optional:application-secrete.properties
spring.application.name=portfolioBackend
server.port=8081

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=surajop609@gmail.com
spring.mail.password=jmbnufcprymqrirx
spring.mail.protocol=smtp

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000

#spring.mail.username=${MAIL_USERNAME}
#spring.mail.password=${MAIL_PASSWORD}